/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.Corredores;

import datos.Carrera;
import datos.Corredor;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logicaNegocio.LogicaNegocio;

/**
 *
 * @author JoseAndres
 */
public class Examen extends javax.swing.JDialog {

    /**
     * Creates new form Examen
     */
    public Examen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        refrescarTabla();
        refrescarListaCarreras();
        
    }
    
    
    public void refrescarTabla() {
    
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre", "DNI", "Fecha de Nacimiento"});
       
        List <Corredor> listaCorredores = LogicaNegocio.getListaCorredores();
        
        for (Corredor corredor : listaCorredores) {
        
            String fechaNacimiento = corredor.getFechaNacimiento();
            
            int dia = Integer.parseInt(fechaNacimiento.substring(0, 1));
            
            if (dia == 0 ) {
            
                dia = Integer.parseInt(fechaNacimiento.substring(1, 2));
           
            }
            
            int mes = Integer.parseInt(fechaNacimiento.substring(3, 4));
            
            System.out.println(mes);
            
            if (mes == 0 ) {
            
                mes = Integer.parseInt(fechaNacimiento.substring(4, 5));

            
            }
                   
            int anio = Integer.parseInt(fechaNacimiento.substring(6, 10));
            
            boolean estaEnCarrera = false;
            
            List <Carrera> listaCarreras = LogicaNegocio.getListaCarreras();
            
            for (int i = 0 ; i < listaCarreras.size() ; i ++) {
                
                for (int x = 0 ; x < listaCarreras.get(i).getListaCorredores().size() ; x++) {
                
                    if (listaCarreras.get(i).getListaCorredores().get(x).getNombre().equals(corredor.getNombre())) {
                    
                        estaEnCarrera = true;
                    
                    }
                
                }
                
            
            }
            
            if (((dia >= 1 && mes >= 1) && anio >= 2000) && estaEnCarrera == true ) {
            
            dtm.addRow(corredor.toArrayString());
            
            jComboBox1.addItem(corredor.getNombre());
           
            estaEnCarrera = false;
            
            }
        
        }
        
        jTableCorredores.setModel(dtm);
        
     } 
    
    public void refrescarListaCarreras() { 
    
        String corredorSeleccionado = (String) jComboBox1.getSelectedItem();
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre", "Fecha", "Lugar", "Número máximo participantes", "Participantes"});
       
        List <Carrera> listaCarreras = LogicaNegocio.getListaCarreras();
        List <Corredor> listaCorredores = LogicaNegocio.getListaCorredores();
  
        for (int x = 0 ; x < listaCarreras.size() ; x ++) {
                    
            for (int y = 0 ; y < listaCarreras.get(x).getListaCorredores().size() ; y ++) {
                        
                if (listaCarreras.get(x).getListaCorredores().get(y).getNombre().equals(corredorSeleccionado)) {
                    
                        dtm.addRow(listaCarreras.get(x).toArrayString());
                            
                             }
                        
                        
                        }
                    
                    
                    }
    
        jTable1.setModel(dtm);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCorredores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCorredores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCorredoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCorredores);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Examen.class, "Examen.jLabel1.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(Examen.class, "Examen.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(Examen.class, "Examen.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCorredoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCorredoresMouseClicked
        
        refrescarListaCarreras();
        
    }//GEN-LAST:event_jTableCorredoresMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        refrescarListaCarreras();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables
}
